### ISSUE TITLE
Failed to update dependencies: Current version of 'kubectl' binaries does not match expected version

### ISSUE THREAD

**Issue by MartyPointer-HTA** [Azure/Bridge-To-Kubernetes#345] opened 2023-12-06 16:34 UTC
Updating plugin to version 2.0.120231128 stops Bridge to Kubernetes from running.

**Mention the platform you are using**
VS Code V1.84.2

**To Reproduce**
1. Install or upgrade to Bridge to Kubernetes plugin V2.0.120231128
2. Run Bridge to Kubernetes via a launch.json file
3. VS Code displays a toast showing the screen shot below (which contains the message "Failed to update dependencies. Current version of 'kubectl' binaries does not match the expected version")
4. Bridge to Kubernetes cannot be configured

**Expected behavior**
Bridge to Kubernetes should create a restore pod and redirect K8s traffic to the application hosted in VS Code

**Screenshots**
![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/138800141/d3579a8a-9c07-4b37-8ccb-bea68fc233e2)

**Logs:**
Log files in C:\Users\Username\AppData\Local\Temp\Bridge To Kubernetes do not report any problems. bridge-mindarocli-yyyy-MM-dd-hh-mm-ss-xxxx.txt log files contain 2 entries for Command.Start and Command.End.
Command.End  = "Result":"Succeeded"

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 119.0.6045.200 

**Additional context**
Trying to manually install the dependencies via the supplied link does not fix the problem
Upgrading installed version of kubectl does not fix the problem
Seen on 3 separate dev PCs
Reverting to the previous version of Bridge to Kubernetes (V2.0.120231004) is the work-around

**Comment by hsubramanianaks** [comment] 2023-12-06 17:16
@MartyPointer-HTA Thanks for raising this concern. Can you check now it is update and should not give this error. Please let me know.

**Comment by hsubramanianaks** [comment] 2023-12-08 16:37
@MartyPointer-HTA Can you please confirm this is working ? if so, we can close this issue. Please let us know if there are any other further issues. Thank you.

**Comment by erceth** [comment] 2023-12-09 00:25
I'm having a similar issue. Isn't 2.0.120231128 the latest?

Mine says failed to update dependencies but doesn't give an error after.
![image](https://github.com/Azure/Bridge-To-Kubernetes/assets/4357758/d6d0dc0d-315d-4ae2-bd30-21fc141006e0)
I'm on an M1 mac.

**Comment by hsubramanianaks** [comment] 2023-12-10 17:34
@erceth this is known issue, and it is caused due to codesign is required on M1 mac which is being worked on. Link [here](https://github.com/Azure/vscode-bridge-to-kubernetes/issues/81#issuecomment-1847496482)

**Comment by MartyPointer-HTA** [comment] 2023-12-11 09:43
> @MartyPointer-HTA Can you please confirm this is working ? if so, we can close this issue. Please let us know if there are any other further issues. Thank you.

Hi @hsubramanianaks, apologies... I assumed the update would be in the form of a new release version and was waiting for it to appear. I can confirm I have re-insalled v2.0.120231128 and no longer see the problem.

Thanks
Marty

**Comment by credo7** [comment] 2023-12-14 21:07
Hello, codesign worked, but have another error now
Everything goes find and on at the last step I am facing crash

Waiting for EndpointManager to come up ...
An unexpected error occurred: 'Failed to launch EndpointManager.'

<img width="1410" alt="Снимок экрана 2023-12-15 в 00 06 06" src="https://github.com/Azure/Bridge-To-Kubernetes/assets/73043804/e60b9465-39ef-4fcf-9d2f-1d003e576a84">

**Comment by hsubramanianaks** [comment] 2023-12-15 18:19
@credo7 This is also known issue which is being investigated on. you are seeing this only after updating to latest, previous versions didn't give this error right ? Alternative you can use service environment variables approach which actually works fine. Apologies for this interruption, we will soon have a release to fix these issues. Thank you.

**Comment by hsubramanianaks** [comment] 2023-12-19 13:35
@credo7 Can you please share your logs when EndpointManager fails. I am able to replicate it but trying to find the root cause of the failure. Thank you.

**Closed** 2024-01-09 15:05 UTC
Labels: bug
