### ISSUE TITLE
Visual Studio tutorial doesn't work

### ISSUE THREAD

**Issue by catmanjan** [Azure/Bridge-To-Kubernetes#40] opened 2022-09-06 01:35 UTC
I am following https://docs.microsoft.com/en-us/visualstudio/bridge/bridge-to-kubernetes-vs

In the prerequisites it says "The [Bridge to Kubernetes extension for Visual Studio](https://aka.ms/bridge-to-k8s-vsc-extension)." but this is a Visual Studio Code extension

After finding the Bridge to Kubernetes extension in VS2022 extensions menu I attempted to follow the rest of the tutorial - I get stuck at "In the project, select Bridge to Kubernetes from the launch settings as shown here:" these are the options I get:

![image](https://user-images.githubusercontent.com/137350/188528657-25dacaf5-15b3-4f83-b9bf-34ad4a037778.png)

**Comment by sabbour** [comment] 2022-09-07 17:37
Duplicate of https://github.com/Azure/Bridge-To-Kubernetes/issues/22.

**Comment by sabbour** [comment] 2022-09-14 22:07
Hi @catmanjan. We're updating the documentation. Did you download and install the Visual Studio 2022 extension from here?
https://marketplace.visualstudio.com/items?itemName=ms-azuretools.mindaro2022

I just installed a fresh copy of Visual Studio 2022, downloaded, and installed the extension and I could see the Bridge to Kubernetes entry in the run profiles.

![3f554ec1-4f36-4b3b-91d4-994b5e496b2e](https://user-images.githubusercontent.com/103856/190271313-090ae6b5-6138-45e2-8521-d24b185dc65b.jpg)

**Comment by qpetraroia** [comment] 2022-09-21 20:47
Closing this issue as we have merged the docs. Thank you @sabbour!

**Closed by qpetraroia** 2022-09-21 20:47 UTC
Labels: documentation
