### ISSUE TITLE
B2K Crashes when debugging code in VS 2022

### ISSUE THREAD

**Issue by Eneuman** [Azure/Bridge-To-Kubernetes#94] opened 2022-11-10 11:58 UTC
**Describe the bug**
If debugging in VS 2022 and standing still on a breakpoint for more then 60 sec, the restore agent crashes and you need to manually redeploy the services again.

The error logg recived in the restore againt pod before crashes is this:

```
2022-11-10T11:36:56.0434535Z | RestorationJob | TRACE | Event: RestorationJob-AgentPing <json>{"eventName":"RestorationJob-AgentPing","properties":{"restorePerformed":"false","numFailedPings":"10","hasConnectedClients":"","result":"Failed"},"metrics":{"durationInMs":12.0}}</json>
2022-11-10T11:37:01.0574230Z | RestorationJob | ERROR | Logging handled exception: System.ArgumentNullException: {"ClassName":"System.ArgumentNullException","Message":"Value cannot be null.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at k8s.AbstractKubernetes.ReadNamespacedDeploymentWithHttpMessagesAsync(String name, String namespaceParameter, Nullable`1 pretty, IReadOnlyDictionary`2 customHeaders, CancellationToken cancellationToken)\n   at k8s.KubernetesExtensions.ReadNamespacedDeploymentAsync(IBasicKubernetes operations, String name, String namespaceParameter, Nullable`1 pretty, CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.<>c__DisplayClass63_0.<<GetV1DeploymentAsync>b__0>d.MoveNext() in /src/common/Kubernetes/KubernetesClient.cs:line 683\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.<>c__DisplayClass75_0`1.<<ClientInvokeWrapperAsync>b__0>d.MoveNext() in /src/common/Kubernetes/KubernetesClient.cs:line 1058\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.BridgeToKubernetes.Common.Utilities.WebUtilities.RetryUntilTimeAsync(Func`2 action, TimeSpan maxWaitTime, CancellationToken cancellationToken) in /src/common/Utilities/WebUtilities.cs:line 112\n   at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.ClientInvokeWrapperAsync[T](Func`1 handler, String operation, CancellationToken cancellationToken) in /src/common/Kubernetes/KubernetesClient.cs:line 1054\n   at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.<>c__DisplayClass24_0.<<ListPodsForDeploymentAsync>b__0>d.MoveNext() in /src/common/Kubernetes/KubernetesClient.cs:line 202\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.<>c__DisplayClass75_0`1.<<ClientInvokeWrapperAsync>b__0>d.MoveNext() in /src/common/Kubernetes/KubernetesClient.cs:line 1058\n--- End of stack trace from previous location where exception was thrown ---\n   at Microsoft.BridgeToKubernetes.Common.Utilities.WebUtilities.RetryUntilTimeAsync(Func`2 action, TimeSpan maxWaitTime, CancellationToken cancellationToken) in /src/common/Utilities/WebUtilities.cs:line 112\n   at Microsoft.BridgeToKubernetes.Common.Kubernetes.KubernetesClient.ClientInvokeWrapperAsync[T](Func`1 handler, String operation, CancellationToken cancellationToken) in /src/common/Kubernetes/KubernetesClient.cs:line 1054\n   at Microsoft.BridgeToKubernetes.DevHostAgent.RestorationJob.RestorationJobApp._GetAgentEndpointAsync(DeploymentPatch deploymentPatch, CancellationToken cancellationToken) in /src/devhostagent.restorationjob/RestorationJobApp.cs:line 236","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147467261,"Source":"KubernetesClient.Basic","WatsonBuckets":null,"ParamName":"namespaceParameter"}
2022-11-10T11:37:01.0586013Z | RestorationJob | TRACE | Event: RestorationJob-AgentPing <json>{"eventName":"RestorationJob-AgentPing","properties":{"restorePerformed":"false","numFailedPings":"11","hasConnectedClients":"","result":"Failed"},"metrics":{"durationInMs":13.0}}</json>
2022-11-10T11:37:01.0590880Z | RestorationJob | ERROR | Failed to ping agent 12 times. Exiting...
2022-11-10T11:37:01.1290258Z | RestorationJob | TRACE | AssemblyLoadContext unloading
2022-11-10T11:37:01.1299823Z | RestorationJob | TRACE | Process exiting...
2022-11-10T11:37:01.1303579Z | RestorationJob | TRACE | Process exited
Stream closed EOF for default/klinikportalservice-restore-71af2-gvknx (lpkrestorationjob)
```

**Mention the platform you are using**
Visual Studio 2022

**To Reproduce**
1. Start Visual Studio 2022 and setup a regular B2K project. 
1. Deploy it to your k8
2. Set a breakpoint in your code
3. Make your breakpoint hit by navigate to the webpage using a browser
4. Wait for 60 sec while examining the log output from the restore pod
5. After the pod has made 12 attempts of RestorationJob-AgentPing it crashed and both the restore pod and your service ends up in a unfixable state.

**Expected behavior**
I should be able to stay still on a breakpoint for mor then 60 sec,

**Desktop (please complete the following information):**
Windows 11

**Comment by Eneuman** [comment] 2022-11-17 18:07
Any news about this issue?
Its realy blocking us in our development cycle :(

**Comment by hsubramanianaks** [comment] 2022-11-29 16:52
@Eneuman Thank you for raising this issue, we are looking into it the root cause, I was NOT able to replicate this issue, even though restore agent failed due to the following error but my cluster went back to original state. 

I think this issue is related to https://github.com/Azure/Bridge-To-Kubernetes/issues/113, I see the same error logs when I debugged in VS 2022 and I don't think it is related to debug point breaking more than 60 seconds.

`Logging handled exception: System.ArgumentNullException: {"ClassName":"System.ArgumentNullException","Message":"Value cannot be null.","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at k8s.AbstractKubernetes.ReadNamespacedDeploymentWithHttpMessagesAsync`

**Comment by Eneuman** [comment] 2022-11-29 17:59
Hi

Yeah #113 looks very similar to my problem and after investigating for a while I would say that this is the root cause. If you stop and restart the debugger just when restore pod is crashed it seems to trigger this behaviour. 

Its okey with me if you want to close this issue and focus on getting #113 fixed :)

**Comment by elenavillamil** [comment] 2023-01-03 23:52
Sounds good. Closing this one since we are working on merging PR for [#113](https://github.com/Azure/Bridge-To-Kubernetes/issues/113).

**Closed by elenavillamil** 2023-01-03 23:52 UTC
Labels: bug
