### ISSUE TITLE
Setting useKubernetesServiceEnvironmentVariables to true causes crash

### ISSUE THREAD

**Issue by tomwganem** [Azure/Bridge-To-Kubernetes#35] opened 2022-09-01 21:26 UTC
This is a copy of https://github.com/microsoft/mindaro/issues/236 which I ran into today while trying to use VSCode and bridge-to-kubernetes on a remote linux machine.

#### Describe the bug
When I set useKubernetesServiceEnvironmentVariables to 'true' (defaults to 'false') in the bridge-to-kubernetes.resource definition in tasks.json and launch the debugger the startup crashes with the following error:

```
Failed to establish a connection. Error: Port 55049 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.
```

#### To Reproduce
After configuring for local tunneling, edit the bridge-to-kubernetes.resource task in tasks.json and set the useKubernetesServiceEnvironmentVariables entry to 'true'. Start a debug session and watch the terminal output to see the crash, followed by a popup asking if you want to abort.

#### Expected behavior
The service should launch locally and run with environment variables set based on those defined in the Kubernetes cluster.

#### Logs
2021-09-30T21:55:53.6974830Z | MindaroCli | TRACE | Event: Command.Start {"properties":{"arguments":"connect --service harmony-service-example --env /var/folders/_6/zt0qbjxd17s4qww0_yvyd_6hh1tml0/t/tmp-33222vinl08njw5l5.env --script /var/folders/_6/zt0qbjxd17s4qww0_yvyd_6hh1tml0/t/tmp-33222vinl08njw5l5.env.cmd --control-port 56952 --ppid 33220 --namespace argo --use-kubernetes-service-environment-variables --local-port 5000","isRoutingEnabled":"false"},"metrics":null}\nOperation context: {"clientRequestId":null,"correlationId":"916f3eab-c305-4084-b51d-f1aca7aabe071633038193418:f873b9ff7bae","requestId":null,"userSubscriptionId":null,"startTime":"2021-09-30T21:55:53.3827450Z","userAgent":"VSCode/1.0.120210803","requestHttpMethod":null,"requestUri":null,"version":"1.0.20210723.6","requestHeaders":{},"loggingProperties":{"applicationName":"MindaroCli","deviceOperatingSystem":"Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Aug 24 20:28:00 PDT 2021; root:xnu-6153.141.401/RELEASE_X86_64","framework":".NET Core 3.1.9","macAddressHash":"dfbe6f9a64e3bb8239cbbb6ade76cf8e2ed251f1e181db90169abb316e750214","processId":34559,"targetEnvironment":"Production","commandId":"f873b9ff7bae"}}
2021-09-30T21:55:53.7753520Z | MindaroCli | TRACE | Running Microsoft.BridgeToKubernetes.Exe.Commands.Connect.ConnectCommand...\nOperation context: {"clientRequestId":null,"correlationId":"916f3eab-c305-4084-b51d-f1aca7aabe071633038193418:f873b9ff7bae","requestId":null,"userSubscriptionId":null,"startTime":"2021-09-30T21:55:53.3827450Z","userAgent":"VSCode/1.0.120210803","requestHttpMethod":null,"requestUri":null,"version":"1.0.20210723.6","requestHeaders":{},"loggingProperties":{"applicationName":"MindaroCli","deviceOperatingSystem":"Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Aug 24 20:28:00 PDT 2021; root:xnu-6153.141.401/RELEASE_X86_64","framework":".NET Core 3.1.9","macAddressHash":"dfbe6f9a64e3bb8239cbbb6ade76cf8e2ed251f1e181db90169abb316e750214","processId":34559,"targetEnvironment":"Production","commandId":"f873b9ff7bae","targetServiceName":"harmony-service-example","isRoutingEnabled":false}}
2021-09-30T21:55:56.1677600Z | MindaroCli | TRACE | Remoting started listening on 56952
2021-09-30T21:56:02.3334980Z | MindaroCli | TRACE | Connection established.\n
2021-09-30T21:56:02.5152590Z | MindaroCli | WARNG | Port 55049 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.
2021-09-30T21:56:02.5155230Z | MindaroCli | ERROR | Port 55049 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.\n
2021-09-30T21:56:02.5159700Z | MindaroCli | TRACE | Stopping workload and cleaning up...\n
2021-09-30T21:56:03.7285030Z | MindaroCli | TRACE | Event: Command.End {"properties":{"arguments":"connect --service harmony-service-example --env /var/folders/_6/zt0qbjxd17s4qww0_yvyd_6hh1tml0/t/tmp-33222vinl08njw5l5.env --script /var/folders/_6/zt0qbjxd17s4qww0_yvyd_6hh1tml0/t/tmp-33222vinl08njw5l5.env.cmd --control-port 56952 --ppid 33220 --namespace argo --use-kubernetes-service-environment-variables --local-port 5000","result":"Failed","failureReason":"Port 55049 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port."},"metrics":{"duration":10092.0}}

#### Environment Details
Client used (VS Code):
mindaro.mindaro@1.0.120210803
Client's version:
Operating System:
macOS Catalina
Additional context
The service launches and runs if I set useKubernetesServiceEnvironmentVariables to 'false', but of course the environment variables are not set in that case.

**Comment by hsubramanianaks** [comment] 2022-09-06 19:44
@tomwganem can you try with latest vscode extension release (20220817) and check if it works?

**Comment by tomwganem** [comment] 2022-09-06 20:19
@hsubramanianaks Still running into this issue
![image](https://user-images.githubusercontent.com/4089491/188730457-7a26aa32-d5a8-4391-913c-9c3c7539c4c6.png)

**Comment by elenavillamil** [comment] 2022-09-09 13:48
Hi @tomwganem, I just ran this locally with sample todo-app on Mac, VSCode (v1.0.120220817) and cli version 1.0.20220816.2 with useKubernetesServiceEnvironmentVariables set to true and it doesnt crash. From the logs you shared the error doesn't seems related to that setting but to a port on your machine been taken. This happens if bridge cant kill the process using the port. 
<img width="1797" alt="Screen Shot 2022-09-02 at 1 58 43 PM" src="https://user-images.githubusercontent.com/4663400/188211541-bbed8964-83a7-4874-80ba-82d4b8d82419.png">

**Comment by qpetraroia** [comment] 2022-09-21 20:49
Hi @tomwganem,

Let us know if you ended up fixing this on your end. We will be closing this issue by EoW if we don't receive a response. Thanks!

**Comment by tomwganem** [comment] 2022-09-21 21:22
Hello,

I've tried again.

To be clear, here's the open ports on the remote ubuntu 20.04 machine, before the trying to start up the bridge

```

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

$ uname -r
5.4.0-125-generic

$ sudo netstat -tulpn             
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:40001         0.0.0.0:*               LISTEN      1361/asperacentral  
tcp        0      0 0.0.0.0:2049            0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:9092            0.0.0.0:*               LISTEN      2429/asperanoded    
tcp        0      0 0.0.0.0:51493           0.0.0.0:*               LISTEN      1289/rpc.mountd     
tcp        0      0 127.0.0.1:10248         0.0.0.0:*               LISTEN      1334/k3s server     
tcp        0      0 127.0.0.1:10249         0.0.0.0:*               LISTEN      1334/k3s server     
tcp        0      0 127.0.0.1:6444          0.0.0.0:*               LISTEN      1334/k3s server     
tcp        0      0 127.0.0.1:38957         0.0.0.0:*               LISTEN      2560243/node        
tcp        0      0 127.0.0.1:40269         0.0.0.0:*               LISTEN      2429/asperanoded    
tcp        0      0 0.0.0.0:5901            0.0.0.0:*               LISTEN      1427/Xtigervnc      
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/init              
tcp        0      0 127.0.0.1:10256         0.0.0.0:*               LISTEN      1334/k3s server     
tcp        0      0 127.0.0.1:10257         0.0.0.0:*               LISTEN      1334/k3s server     
tcp        0      0 127.0.0.1:10258         0.0.0.0:*               LISTEN      1334/k3s server     
tcp        0      0 127.0.0.1:10259         0.0.0.0:*               LISTEN      1334/k3s server     
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      1109/systemd-resolv 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1314/sshd: /usr/sbi 
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN      2424942/cupsd       
tcp        0      0 127.0.0.1:31415         0.0.0.0:*               LISTEN      1319/asperaredisd 1 
tcp        0      0 127.0.0.1:10010         0.0.0.0:*               LISTEN      1944/containerd     
tcp        0      0 0.0.0.0:40827           0.0.0.0:*               LISTEN      -                   
tcp        0      0 0.0.0.0:56411           0.0.0.0:*               LISTEN      1289/rpc.mountd     
tcp        0      0 127.0.0.1:45661         0.0.0.0:*               LISTEN      1361/asperacentral  
tcp        0      0 0.0.0.0:34943           0.0.0.0:*               LISTEN      1289/rpc.mountd     
tcp6       0      0 :::2049                 :::*                    LISTEN      -                   
tcp6       0      0 :::10250                :::*                    LISTEN      1334/k3s server     
tcp6       0      0 :::6443                 :::*                    LISTEN      1334/k3s server     
tcp6       0      0 :::5901                 :::*                    LISTEN      1427/Xtigervnc      
tcp6       0      0 :::111                  :::*                    LISTEN      1/init              
tcp6       0      0 :::57107                :::*                    LISTEN      1289/rpc.mountd     
tcp6       0      0 :::40693                :::*                    LISTEN      1289/rpc.mountd     
tcp6       0      0 127.0.0.1:3350          :::*                    LISTEN      1347/xrdp-sesman    
tcp6       0      0 :::22                   :::*                    LISTEN      1314/sshd: /usr/sbi 
tcp6       0      0 :::48089                :::*                    LISTEN      1289/rpc.mountd     
tcp6       0      0 :::3389                 :::*                    LISTEN      1381/xrdp           
tcp6       0      0 :::33949                :::*                    LISTEN      -                   
udp        0      0 0.0.0.0:56897           0.0.0.0:*                           1289/rpc.mountd     
udp        0      0 0.0.0.0:57022           0.0.0.0:*                           1289/rpc.mountd     
udp        0      0 127.0.0.53:53           0.0.0.0:*                           1109/systemd-resolv 
udp        0      0 0.0.0.0:68              0.0.0.0:*                           891/dhclient        
udp        0      0 0.0.0.0:68              0.0.0.0:*                           892/dhclient        
udp        0      0 0.0.0.0:111             0.0.0.0:*                           1/init              
udp        0      0 10.42.0.1:123           0.0.0.0:*                           1293/ntpd           
udp        0      0 10.42.0.0:123           0.0.0.0:*                           1293/ntpd           
udp        0      0 9.30.141.31:123         0.0.0.0:*                           1293/ntpd           
udp        0      0 10.11.102.219:123       0.0.0.0:*                           1293/ntpd           
udp        0      0 127.0.0.1:123           0.0.0.0:*                           1293/ntpd           
udp        0      0 0.0.0.0:123             0.0.0.0:*                           1293/ntpd           
udp        0      0 0.0.0.0:8472            0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:41465           0.0.0.0:*                           984/avahi-daemon: r 
udp        0      0 0.0.0.0:631             0.0.0.0:*                           2424943/cups-browse 
udp        0      0 0.0.0.0:2049            0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:59649           0.0.0.0:*                           -                   
udp        0      0 0.0.0.0:52552           0.0.0.0:*                           1289/rpc.mountd     
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           984/avahi-daemon: r 
udp6       0      0 :::47828                :::*                                -                   
udp6       0      0 :::111                  :::*                                1/init              
udp6       0      0 :::123                  :::*                                1293/ntpd           
udp6       0      0 :::42716                :::*                                984/avahi-daemon: r 
udp6       0      0 :::2049                 :::*                                -                   
udp6       0      0 :::44715                :::*                                1289/rpc.mountd     
udp6       0      0 :::53639                :::*                                1289/rpc.mountd     
udp6       0      0 :::46176                :::*                                1289/rpc.mountd     
udp6       0      0 :::5353                 :::*                                984/avahi-daemon: r 
```

Here's the vscode version I'm using
```sh
Version: 1.71.2
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:05:37.721Z (1 wk ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No
```

Trying to connect with Bridge-To-Kubernetes results in the same issue
```sh
Bridge to Kubernetes initialization (VS Code v1.71.2 - Extension v1.0.120220817)
Logs: /home/tganem/.vscode-server/data/logs/20220921T141352/exthost1/mindaro.mindaro/mindaro-vscode-2022-09-21T21-14-01.411Z.txt
Waiting for 'f4-back-end-puma-6dcc5c8dcc-dlr92' in namespace 'review-spark3' to reach running state...
Deployment 'review-spark3/f4-back-end-puma' patched to run agent.
Remote agent deployed in container 'puma' in pod 'f4-back-end-puma-6dcc5c8dcc-dlr92'.
Preparing to run Bridge To Kubernetes configured as pod review-spark3/f4-back-end-puma-6dcc5c8dcc-dlr92 ...
Connection established.
Service 'resque-redis-master' is available on 127.0.0.1:55049.
Service 'spark-spark-app-a8-engine-ui-svc' is available on 127.0.0.1:55050.
Service 'aej' is available on 127.0.0.1:55051.
Service 'cache-redis-master' is available on 127.0.0.1:55052.
Service 'postgresql' is available on 127.0.0.1:55053.
Service 'packages-trans-ack-consumer' is available on 127.0.0.1:55054.
Service 'aspera-on-cloudx-aocx-server' is available on 127.0.0.1:55055.
Service 'a8-srs-spark-app-ui-svc' is available on 127.0.0.1:55056.
Service 'dashboard' is available on 127.0.0.1:55057.
Service 'resque-web' is available on 127.0.0.1:55058.
Service 'mailhog' is available on 127.0.0.1:55059.
Service 'mailhog' is available on 127.0.0.1:55060.
Service 'spark-spark-nginx-a8-engine' is available on 127.0.0.1:55061.
Service 'a8-srs-nginx' is available on 127.0.0.1:55062.
Service 'spark-spark-app-validator-ui-svc' is available on 127.0.0.1:55063.
Service 'f4-back-end-internal' is available on 127.0.0.1:55064.
Service 'platform' is available on 127.0.0.1:55065.
Service 'mysql' is available on 127.0.0.1:55066.
Service 'aoc-help' is available on 127.0.0.1:55067.
Service 'f4-back-end-short' is available on 127.0.0.1:55068.
Service 'f4-back-end-short' is available on 127.0.0.1:55069.
Service 'packages-upload-status-consumer' is available on 127.0.0.1:55070.
Service 'workflow-engine' is available on 127.0.0.1:55071.
Service 'event-bus' is available on 127.0.0.1:55072.
Service 'cassandra-monitoring' is available on 127.0.0.1:55073.
Service 'a8-be' is available on 127.0.0.1:55074.
Service 'a8-be' is available on 127.0.0.1:55075.
Service 'emissary-ingress-admin' is available on 127.0.0.1:55076.
Service 'emissary-ingress-admin' is available on 127.0.0.1:55077.
Service 'f4-back-end-puma' is available on 127.0.0.1:55078.
Service 'spark-spark-nginx-validator' is available on 127.0.0.1:55079.
Service 'cassandra-svc' is available on 127.0.0.1:55080.
Service 'cassandra-svc' is available on 127.0.0.1:55081.
Service 'ambassador-auth-jwt' is available on 127.0.0.1:55082.
Service 'spark-spark-app-endpoints' is available on 127.0.0.1:55083.
Service 'usageportal' is available on 127.0.0.1:55084.
Service 'packages-delivery-request-consumer' is available on 127.0.0.1:55085.
Service 'node-executor-web' is available on 127.0.0.1:55086.
Service 'kafka-app-kafka-bootstrap' is available on 127.0.0.1:55087.
Service 'kafka-app-kafka-bootstrap' is available on 127.0.0.1:55088.
Service 'emissary-ingress' is available on 127.0.0.1:55089.
Service 'emissary-ingress' is available on 127.0.0.1:55090.
Service 'kafka-app-zookeeper-client' is available on 127.0.0.1:55091.
Service 'automation-puma' is available on 127.0.0.1:55092.
Service 'resque-redis-master-0.resque-redis-headless' is available on 127.0.0.1:55093.
Port 55093 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.
Stopping workload and cleaning up...
Failed to restore service at 'review-spark3/f4-back-end-puma-97fffd898-zx4sr/puma'.
Failed to establish a connection. Error: Port 55093 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.
```

![image](https://user-images.githubusercontent.com/4089491/191612870-068696b3-7e7e-4139-a488-582f6613cd5a.png)

**Comment by elenavillamil** [comment] 2022-10-05 18:28
@tomwganem, thank you for the extra info! This does help point us in some direction. It seems from your logs that bridge is trying to use port 55093 for two services. It uses it for resque-redis-master-0.resque-redis-headless and then it tries to use it again and fails. I will start looking into this further this week and update here when I have something.

**Comment by elenavillamil** [comment] 2022-10-11 14:29
Hello @tomwganem, we have an idea of where things are going wrong but we are unable to reproduce this bug with our sample application. Is there a sample of your application you could share that reproduces the issue?

**Comment by GKilm** [comment] 2022-10-18 08:04
@elenavillamil I have the same wrong when I try debuging the pod `default-region` which is created by the project  [cloudpods](https://github.com/yunionio/cloudpods).
Here is the file `task.json`.
```json
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "bridge-to-kubernetes.resource",
            "type": "bridge-to-kubernetes.resource",
            "resource": "default-region",
            "resourceType": "service",
            "ports": [
                54210
            ],
            "targetCluster": "kubernetes",
            "targetNamespace": "onecloud",
            "useKubernetesServiceEnvironmentVariables": true,
            "isolateAs": "root-b11f"
        }
    ]
}
```

**Logs**
```
Bridge to Kubernetes initialization (VS Code v1.72.2 - Extension v1.0.120220915)
Logs: /root/.vscode-server/data/logs/20221018T084720/exthost1/mindaro.mindaro/mindaro-vscode-2022-10-18T00-48-11.362Z.txt
Connect operation failed.
Stopping workload and cleaning up...
An unexpected error occurred: 'The JSON value could not be converted to k8s.Models.V1ServiceStatus. Path: $.status | LineNumber: 0 | BytePositionInLine: 67.'
To see our active issues or file a bug report, please visit https://aka.ms/bridge-to-k8s-report.
For diagnostic information, see logs at '/tmp/Bridge To Kubernetes'.
Failed to establish a connection. Error: Connect operation failed.
An unexpected error occurred: 'The JSON value could not be converted to k8s.Models.V1ServiceStatus. Path: $.status | LineNumber: 0 | BytePositionInLine: 67.'
To see our active issues or file a bug report, please visit https://aka.ms/bridge-to-k8s-report.
For diagnostic information, see logs at '/tmp/Bridge To Kubernetes'.

Routing successfully enabled for service through pod 'root-default-region-7549678866-25xsk' in namespace 'onecloud'.
Waiting for 'root-default-region-7549678866-25xsk' in namespace 'onecloud' to reach running state...
Pod 'root-default-region-7549678866-25xsk' created in namespace 'onecloud'.
Remote agent deployed in container 'region' in pod 'root-default-region-7549678866-25xsk'.
Preparing to run Bridge To Kubernetes configured as pod onecloud/root-default-region-7549678866-25xsk ...
Connection established.
Service 'default-etcd-client' is available on 127.0.0.1:55049.
Service 'default-web' is available on 127.0.0.1:55050.
Service 'default-web' is available on 127.0.0.1:55051.
Service 'default-web' is available on 127.0.0.1:55052.
Service 'default-etcd-8qkq2l25fj.default-etcd' is available on 127.0.0.1:55053.
Service 'default-etcd-8qkq2l25fj.default-etcd' is available on 127.0.0.1:55054.
Port 55053 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.
Stopping workload and cleaning up...
Restore: Pod 'root-default-region-7549678866-25xsk' deleted.
Failed to establish a connection. Error: Port 55053 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.
```

**Comment by tomwganem** [comment] 2022-10-18 18:50
@elenavillamil To your question to me, you can try the bitnami redis chart. That's what failing for me. Maybe a problem with headless services?

**Comment by elenavillamil** [comment] 2022-11-18 14:50
I just want to give a quick update for this. Fix has been merged and we are starting a release with the changes. ETA to have this released in prod is next week.

**Comment by tomwganem** [comment] 2022-11-18 19:30
@elenavillamil Awesome. Thanks so much :)

**Comment by elenavillamil** [comment] 2022-12-06 21:08
@tomwganem, fix for this has been released. I am closing this issue, but please feel free to reopen if you still see this problem.

Thank you!
Elena

**Closed** 2022-12-06 21:09 UTC
Labels: bug, investigation needed
