### ISSUE TITLE
Following the tutoral  gives a "socket hang up"

### ISSUE THREAD

**Issue by buckleyGI** [Azure/Bridge-To-Kubernetes#150] opened 2023-01-21 15:30 UTC
**Describe the bug**
When following the Tutorial: Use Bridge to Kubernetes the endpoints becomes unavailable after the debugger is attached.
We get a "socket hang up" on the /api/todos endpoint

https://learn.microsoft.com/en-us/visualstudio/bridge/bridge-to-kubernetes-vs

We had the use the workaround described here https://github.com/microsoft/mindaro/issues/26#issuecomment-696391176

Note that everything is working find until the point we attach the debugger

**Mention the platform you are using**
Visual Studio 2022 17.3
Bridge to Kubernetes 2022 Version 	3.1.20230118.1

**To Reproduce**
1. Follow the tutorial on https://learn.microsoft.com/en-us/visualstudio/bridge/bridge-to-kubernetes-vs
2. Stop After performing step 6 of "Connect to your cluster"
3. Observe that the endpoint /api/todos gives a "socket hang up"

**Expected behavior**
The tasks that were already entered

**Screenshots**
2 Screenshots:
1. The error that the front end gives
2. the endpoint that is in a faulty state

![image](https://user-images.githubusercontent.com/2102864/213873968-29952554-c811-4336-bde5-0b63c297cd55.png)
![image](https://user-images.githubusercontent.com/2102864/213873970-10a853f1-d6c6-4194-9cfa-1b13bedf7011.png)

**Desktop (please complete the following information):**
- Windows 11 Enterprise Build 22000.co_release.210604-1628
- Firefox v 109.0

**Comment by hsubramanianaks** [comment] 2023-01-23 13:54
@buckleyGI Thanks for raising this issue, we will look into it.

**Comment by hsubramanianaks** [comment] 2023-01-23 14:11
@buckleyGI I am not able to reproduce this with latest VS extension in VS 2022. This happens sometimes if you are connected to VPN and VPN blocks the socket? Can you try without VPN? Please let me know, thanks. 

<img width="883" alt="image" src="https://user-images.githubusercontent.com/105889062/214060157-512553b8-2fe3-46ca-81c6-6cb4bad329da.png">

<img width="701" alt="image" src="https://user-images.githubusercontent.com/105889062/214060227-bc5e4204-c500-44a7-9ff5-a7b9ce230c3d.png">

**Comment by buckleyGI** [comment] 2023-01-23 15:31
Hi @hsubramanianaks Thanks for your reply. The VPN wasn't enabled
I am now at work (and thus without VPN) and now get 
![image](https://user-images.githubusercontent.com/2102864/214080081-c85445cc-fe69-4987-8568-9934285c0ae0.png)

**Comment by buckleyGI** [comment] 2023-01-23 15:37
I redid the workaround as described [here](https://github.com/microsoft/mindaro/issues/26#issuecomment-696391176) and can connect to the cluster again. The same message is given "socket hang up" at work without vpn

**Comment by hsubramanianaks** [comment] 2023-01-23 17:03
@buckleyGI can you share the logs ? Thank you.

**Comment by Eneuman** [comment] 2023-01-25 09:05
> Hi @hsubramanianaks Thanks for your reply. The VPN wasn't enabled
> 
> I am now at work (and thus without VPN) and now get "Refresh not supported".
> 
> ![image](https://user-images.githubusercontent.com/2102864/214080081-c85445cc-fe69-4987-8568-9934285c0ae0.png)
> 
> 

You can get around the "Refresh not supported" problem by running any kubectl command from a command window. The problem is that your token is expired and KubernetesClient does not yet support refreshing the token using your refresh token when using AKS.

**Comment by elenavillamil** [comment] 2023-02-16 22:31
@buckleyGI can you confirm that running kubectl command solves your issue? If so I will go ahead and close this issue.

**Comment by elenavillamil** [comment] 2023-03-13 16:49
Closing due ot inactivity but please feel free to re-open if you are still stuck.

**Closed by elenavillamil** 2023-03-13 16:49 UTC
Labels: waiting for response
