### ISSUE TITLE
Permission denied error in 'Adding rules to routing table' on linux(openSUSE)

### ISSUE THREAD

**Issue by smbd** [Azure/Bridge-To-Kubernetes#32] opened 2022-08-30 10:09 UTC
**Describe the bug**
Could not complete setup with bellow errror log(/tmp/Bridge To Kubernetes/bridge-endpointmanager-....txt)

```
2022-08-30T09:56:54.8363627Z | EndpointManager | TRACE | Received request segment: '{"argument":[{"dnsName":"todos-db","localIP":null,"ports":[{"localPort":55049,"remotePort":27017,"protocol":"TCP"}],"isExternalEndpoint":false,"isInWorkloadNamespace":true},{"dnsName":"database-api","localIP":null,"ports":[{"localPort":55050,"remotePort":80,"protocol":"TCP"}],"isExternalEndpoint":false,"isInWorkloadNamespace":true},{"dnsName":"stats-api","localIP":null,"ports":[{"localPort":55051,"remotePort":80,"protocol":"TCP"}],"isExternalEndpoint":false,"isInWorkloadNamespace":true},{"dnsName":"stats-cache","localIP":null,"ports":[{"localPort":55052,"remotePort":6379,"protocol":"TCP"}],"isExternalEndpoint":false,"isInWorkloadNamespace":true},{"dnsName":"stats-queue","localIP":null,"ports":[{"localPort":55053,"remotePort":5672,"protocol":"TCP"}],"isExternalEndpoint":false,"isInWorkloadNamespace":true},{"dnsName":"frontend","localIP":null,"ports":[{"localPort":55054,"remotePort":80,"protocol":"TCP"}],"isExternalEndpoint":false,"isInWorkloadNamespace":true}],"apiname":"AllocateIP","correlationId":"29350fa4-d86a-4eb7-b094-a4367d8f35a81661853327401:7d9c80d35177:64bf8713aef2:2e254ae4ad7e"}<EOF>' of size 1109
2022-08-30T09:56:54.8371903Z | EndpointManager | TRACE | Allocating IP...\nOperation context: <json>{"clientRequestId":null,"correlationId":"29350fa4-d86a-4eb7-b094-a4367d8f35a81661853327401:7d9c80d35177:64bf8713aef2:2e254ae4ad7e:0b2fd8690088","requestId":null,"userSubscriptionId":null,"startTime":"2022-08-30T09:51:23.3840112Z","userAgent":"EndpointManager/1.0.20220816.2","requestHttpMethod":null,"requestUri":null,"version":"1.0.20220816.2","requestHeaders":{},"loggingProperties":{"applicationName":"EndpointManager","deviceOperatingSystem":"Linux 5.3.18-150300.59.76-default #1 SMP Thu Jun 16 04:23:47 UTC 2022 (2cc2ade)","framework":".NET Core 3.1.9","macAddressHash":"cc0cb0cbd2721c64e2fb9c6790b02bbc7ad534fc5869b2abb08e886ea84e2d8d","processId":28524,"targetEnvironment":"Production"}}</json>
2022-08-30T09:56:54.8373159Z | EndpointManager | TRACE | Allocated IP 127.1.1.7
2022-08-30T09:56:54.8373904Z | EndpointManager | TRACE | Allocating IP...
2022-08-30T09:56:54.8374387Z | EndpointManager | TRACE | Allocated IP 127.1.1.8
2022-08-30T09:56:54.8374853Z | EndpointManager | TRACE | Allocating IP...
2022-08-30T09:56:54.8375318Z | EndpointManager | TRACE | Allocated IP 127.1.1.9
2022-08-30T09:56:54.8375832Z | EndpointManager | TRACE | Allocating IP...
2022-08-30T09:56:54.8376315Z | EndpointManager | TRACE | Allocated IP 127.1.1.10
2022-08-30T09:56:54.8376733Z | EndpointManager | TRACE | Allocating IP...
2022-08-30T09:56:54.8377199Z | EndpointManager | TRACE | Allocated IP 127.1.1.11
2022-08-30T09:56:54.8377726Z | EndpointManager | TRACE | Allocating IP...
2022-08-30T09:56:54.8378179Z | EndpointManager | TRACE | Allocated IP 127.1.1.12
2022-08-30T09:56:54.8379039Z | EndpointManager | TRACE | Adding rules to routing table...
2022-08-30T09:56:54.8379631Z | EndpointManager | TRACE | Running 'iptables --table nat --append PREROUTING -p tcp --dst 127.1.1.7 --dport 27017 --jump DNAT --to-destination 127.1.1.7:55049'
2022-08-30T09:56:54.8387770Z | EndpointManager | TRACE | Event: IP-AddRoutingRules <json>{"properties":{"result":"Failed"},"metrics":{"durationInMs":0.0}}</json>
2022-08-30T09:56:54.8389074Z | EndpointManager | TRACE | Event: IP-AllocateIP <json>{"properties":{"result":"Failed"},"metrics":{"durationInMs":1.0}}</json>
2022-08-30T09:56:54.8433691Z | EndpointManager | ERROR | Logging handled exception: System.ComponentModel.Win32Exception: {"ClassName":"System.ComponentModel.Win32Exception","Message":"Permission denied","Data":null,"InnerException":null,"HelpURL":null,"StackTraceString":"   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)\n   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)\n   at System.Diagnostics.Process.Start()\n   at Microsoft.BridgeToKubernetes.Common.IO.Platform.Execute(String executable, String command, Action`1 stdOutCallback, Action`1 stdErrCallback, IDictionary`2 envVariables, TimeSpan timeout, CancellationToken cancellationToken, String& stdOutOutput, String& stdErrOutput)\n   at Microsoft.BridgeToKubernetes.Common.IO.Platform.Execute(String executable, String command, Action`1 logCallback, IDictionary`2 envVariables, TimeSpan timeout, CancellationToken cancellationToken, String& output)\n   at Microsoft.BridgeToKubernetes.Common.IP.IPManager.RunUtility(String executable, String args, CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.Common.IP.IPManager.AddRoutingRules(IEnumerable`1 endpoints, CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.Common.IP.IPManager.AllocateIPs(IEnumerable`1 endpoints, Boolean addRoutingRules, CancellationToken cancellationToken)\n   at Microsoft.BridgeToKubernetes.EndpointManager.EndpointManager.<>c__DisplayClass23_0.<ProcessClientCallsAsync>b__1()\n   at Microsoft.BridgeToKubernetes.EndpointManager.EndpointManager.InvokeWithExceptionHandler[T](Func`1 handler)","RemoteStackTraceString":null,"RemoteStackIndex":0,"ExceptionMethod":null,"HResult":-2147467259,"Source":"System.Diagnostics.Process","WatsonBuckets":null,"NativeErrorCode":13}
2022-08-30T09:56:54.8462765Z | EndpointManager | TRACE | Sending response: '{"value":null,"isSuccess":false,"errorMessage":"Permission denied","errorType":"InvalidOperation"}'
2022-08-30T09:56:54.8463717Z | EndpointManager | TRACE | 103 bytes were sent.
```

**Mention the platform you are using**
vscode

**To Reproduce**

trying tutorial: https://docs.microsoft.com/en-us/visualstudio/bridge/bridge-to-kubernetes-sample

1. 'Click the start button next to Run Script: dev with Kubernetes.'
2. An error occurred, and TERMINAL output is bellow
```
Executing task: bridge-to-kubernetes.resource 

Redirecting Kubernetes service stats-api to your machine...
Target cluster: sri-dev
Current cluster: sri-dev
Target namespace: simamura
Current namespace: simamura
Target service name: stats-api
Target service ports: 3001
Using kubernetes service environment variables: false

Retrieving the current context and credentials...
Validating the credentials to access the cluster...
Validating the requirements to replicate resources locally...
Redirecting traffic from the cluster to your machine...
Waiting for 'stats-api-56d8db88cd-w7dbc' in namespace 'simamura' to reach running state...
Deployment 'simamura/stats-api' patched to run agent.
Remote agent deployed in container 'stats-api' in pod 'stats-api-56d8db88cd-w7dbc'.
Preparing to run Bridge To Kubernetes configured as pod simamura/stats-api-56d8db88cd-w7dbc ...
Connection established.
Connect operation failed.
Stopping workload and cleaning up...
Restore: Deployment 'stats-api' restored to original state with image 'azdspublic/todo-app-stats-api'.
An unexpected error occurred: 'Permission denied'
To see our active issues or file a bug report, please visit https://aka.ms/bridge-to-k8s-report.

Error: Failed to establish a connection. Error: Connect operation failed.
An unexpected error occurred: 'Permission denied'
To see our active issues or file a bug report, please visit https://aka.ms/bridge-to-k8s-report.


 *  The terminal process terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Expected behavior**
Finish to connect k8s cluster.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: openSUSE Leap 15.3
 - Browser: not running
 - Version: VS Code v1.70.2 - Extension v1.0.120220817

**Additional context**
- Elevation privillage dialog was open. And enter correct root user's password.
- As root user, iptables command in error log is succes.
```
# whoami
root
# iptables --table nat --append PREROUTING -p tcp --dst 127.1.1.7 --dport 27017 --jump DNAT --to-destination 127.1.1.7:55049
# iptables -n --table nat -L PREROUTING
Chain PREROUTING (policy ACCEPT)
target     prot opt source               destination
DOCKER     all  --  0.0.0.0/0            0.0.0.0/0            ADDRTYPE match dst-type LOCAL
DNAT       tcp  --  0.0.0.0/0            127.1.1.7            tcp dpt:27017 to:127.1.1.7:55049
```

**Comment by elenavillamil** [comment] 2022-09-14 18:44
Did you see a pop up asking for elevated access and did you approve it? Bridge needs elevated access to update host files.

**Comment by smbd** [comment] 2022-09-16 02:38
Sure, when failed, I can see pod's hostname and 127.1.1.X IP address in /etc/hosts

**Comment by elenavillamil** [comment] 2022-10-04 19:59
I am not able to reproduce this locally. Could you share the local logs you get for this run?

Thank you.

**Comment by elenavillamil** [comment] 2022-11-08 20:51
Pinging back. Just as FYI, we will be closing this ticket next week if there is no update. Thank you.

**Closed** 2022-11-15 20:44 UTC
Labels: investigation needed, waiting for response
