### ISSUE TITLE
App debug - connect/disconnect - multiple entries warning related to bridge

### ISSUE THREAD

**Issue by VaclavK** [Azure/Bridge-To-Kubernetes#74] opened 2022-10-12 15:15 UTC
I have been using bridge for little while and running/debugging an app - connecting/disconnecting and refreshing K8 real cluster

I see following warnings now

Warning: spec.template.spec.containers[0].env[5].name: duplicate name "BRIDGE_COLLECT_TELEMETRY"
Warning: spec.template.spec.containers[0].env[6].name: duplicate name "BRIDGE_COLLECT_TELEMETRY"
Warning: spec.template.spec.containers[0].env[7].name: duplicate name "BRIDGE_COLLECT_TELEMETRY"
Warning: spec.template.spec.containers[0].env[8].name: duplicate name "BRIDGE_COLLECT_TELEMETRY"
Warning: spec.template.spec.containers[0].env[9].name: duplicate name "BRIDGE_COLLECT_TELEMETRY"
Warning: spec.template.spec.containers[0].env[11].name: duplicate name "CONSOLE_VERBOSITY"
Warning: spec.template.spec.containers[0].env[12].name: duplicate name "CONSOLE_VERBOSITY"
Warning: spec.template.spec.containers[0].env[13].name: duplicate name "CONSOLE_VERBOSITY"
Warning: spec.template.spec.containers[0].env[14].name: duplicate name "CONSOLE_VERBOSITY"
Warning: spec.template.spec.containers[0].env[15].name: duplicate name "CONSOLE_VERBOSITY"
Warning: spec.template.spec.containers[0].env[17].name: duplicate name "BRIDGE_CORRELATION_ID"
Warning: spec.template.spec.containers[0].env[18].name: duplicate name "BRIDGE_CORRELATION_ID"
Warning: spec.template.spec.containers[0].env[19].name: duplicate name "BRIDGE_CORRELATION_ID"
Warning: spec.template.spec.containers[0].env[20].name: duplicate name "BRIDGE_CORRELATION_ID"
Warning: spec.template.spec.containers[0].env[21].name: duplicate name "BRIDGE_CORRELATION_ID"

etc.

indeed I can see in workload YAML these are duplicated...

AM I correct in saying this is bridge failing to clean up after itself?

**Comment by elenavillamil** [comment] 2022-10-21 19:25
Hi @VaclavK, we currently unable to reproduce your issue. Could you provide us more details. For instance are you running using useKubernetesServiceEnvironmentVariables set to true or false? Which OS are you running? Is this VSCode, VS or are you using CLI directly? Can you provide your deployment and service yaml spec? Also if you could provide full output it would help us as well.

Thank you!

**Comment by VaclavK** [comment] 2022-10-26 10:37
I cannot at the moment repro myself...

running in VS 2022 (17.3.6) under W10 X64 ARM

I will be doing more debug in the next few days so if I can catch more on this, I will update the ticket

**Comment by elenavillamil** [comment] 2022-10-26 23:15
@VaclavK, thank you for getting back to us. We will keep the ticket open for a couple weeks and then we will close it if no repo. Feel free to re-open at any point if it is closed and you ran into this again.

Thank you!
Elena

**Comment by VaclavK** [comment] 2022-11-22 10:16
managed to reproduce again

this time it was VS Code... 

a) connection to bridge A
b) disconnect - "failed to disconnect, socket hang" or similar message
c) connection B - which is likely where it duplicated the environment variables (see below) 
d) to disconnect fully I had to do rollout undo deployment and then I got the warning

Warning: spec.template.spec.containers[0].env[8].name: duplicate name "BRIDGE_COLLECT_TELEMETRY"
Warning: spec.template.spec.containers[0].env[9].name: duplicate name "CONSOLE_VERBOSITY"
Warning: spec.template.spec.containers[0].env[10].name: duplicate name "BRIDGE_CORRELATION_ID"

this is the env section of describe deployment


      BRIDGE_COLLECT_TELEMETRY:               True
      CONSOLE_VERBOSITY:                      Verbose
      BRIDGE_CORRELATION_ID:                  5a943e69-fe91-4c51-8b0a-884c19c6ea171669030492530:75e9835804b5:002b487eed44
      BRIDGE_COLLECT_TELEMETRY:               True
      CONSOLE_VERBOSITY:                      Verbose
      BRIDGE_CORRELATION_ID:                  5a943e69-fe91-4c51-8b0a-884c19c6ea171669030492530:d9c37dcf2a6c:409561662b0

**Comment by elenavillamil** [comment] 2022-12-13 19:05
Correct, if disconnect fails and then you restart bridge you will run into that issue. After disconnecting always check that your cluster is restored before starting another session. If disconnect fails, bridge has a check that will trigger the restore job if connection hasn't been active for more than 1 minute. So giving it 1 to 2 minutes should also restore everything without needing to do a rollout.

**Closed** 2022-12-13 19:09 UTC
