### ISSUE TITLE
Port already in use when initiating bridge

### ISSUE THREAD

**Issue by maj** [Azure/Bridge-To-Kubernetes#52] opened 2022-09-15 13:56 UTC
I'm trying to enable a bridge between my local and a Kubernetes cluster running in Ubuntu. Some of the services are available on multiple ports, i.e. Vault. When I start the configuration I get the following error:

    Service 'demoapp' is available on 127.0.0.1:55059. 
    Service 'vault-0.vault-internal' is available on 127.0.0.1:55060.
    Service 'vault-0.vault-internal' is available on 127.0.0.1:55061.
    Port 55060 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.

It seems like Bridge to Kubernetes is trying to allocate the same port twice. I don't think it's an issue with the local computer since before this I was also running Confluent and it got past these ports before having the same issue.

    Service 'my-confluent-cp-zookeeper-2.my-confluent-cp-zookeeper-headless' is available on 127.0.0.1:55073.
    Service 'my-confluent-cp-zookeeper-2.my-confluent-cp-zookeeper-headless' is available on 127.0.0.1:55074.
    Port 55073 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.

Can you help me get this working? Thanks

**Comment by epolar** [comment] 2022-09-20 10:11
same problem, Would you resolve it?

**Comment by elenavillamil** [comment] 2022-09-22 17:58
Also, providing the logs in the log folder will also help investigate this further. When bridge starts in the output window it lets you know the folder where it will put the logs for the run.

**Comment by elenavillamil** [comment] 2022-10-11 17:13
Also can you confirm if you have useKubernetesServiceEnvironmentVariables set to true when running into this issue?

**Comment by NPellet** [comment] 2022-10-18 13:58
I also observice this and I can confirm it on my side, I have the flag on.

**Comment by NPellet** [comment] 2022-10-19 08:36
It seems to me that another service has already been assigned this port:
```
Service 'otel-collector' is available on 127.1.1.11:4317.
Service 'otel-collector' is available on 127.1.1.11:4318.
...
Service 'simplest-collector-headless' is available on 127.1.1.18:4318.
Port 4318 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.
```

**Comment by NPellet** [comment] 2022-10-19 08:58
```
2022-10-19T08:55:15.158Z | Common Extension Root    | TRACE | query-expfeature <json>{"ABExp.queriedFeature":"vscode.mindaroBinariesVersion-doesnotexist"}</json>
2022-10-19T08:55:15.158Z | Common Extension Root    | TRACE | Call to ExP returned version 'undefined' <json>{}</json>
2022-10-19T08:55:15.158Z | Common Extension Root    | TRACE | Resolved expected CLI version '1.0.20220816.2' <json>{}</json>
2022-10-19T08:55:15.162Z | Common Extension Root    | TRACE | Event: binaries-utility-version-v1 <json>{}</json>
2022-10-19T08:55:15.163Z | Common Extension Root    | TRACE | Trying to initialize the workspace folder profile-service for Connect <json>{}</json>
2022-10-19T08:55:15.163Z | Common Extension Root    | TRACE | Connect initialization started on profile-service <json>{}</json>
2022-10-19T08:55:15.163Z | Common Extension Root    | TRACE | Event: connect-initialization-success <json>{"workspacesCommonId":"ddb7fdc0-6a9e-e10f-80f4-38abe057b83c"}</json>
2022-10-19T08:55:15.163Z | Common Extension Root    | TRACE | Making sure that the CLI is present locally, by downloading it if needed <json>{}</json>
2022-10-19T08:55:15.163Z | Common Extension Root    | TRACE | Making sure that the CLI is present locally, by downloading it if needed <json>{}</json>
2022-10-19T08:55:15.164Z | Common Extension Root    | TRACE | Successfully determined the CLI binary path: c:\Users\Norman\AppData\Roaming\Code\User\globalStorage\mindaro.mindaro\file-downloader-downloads\binaries\dsc.exe <json>{}</json>
2022-10-19T08:55:15.165Z | Common Extension Root    | TRACE | Successfully determined the kubectl binary path: c:\Users\Norman\AppData\Roaming\Code\User\globalStorage\mindaro.mindaro\file-downloader-downloads\binaries\kubectl\win\kubectl.exe <json>{}</json>
2022-10-19T08:55:15.993Z | Common Extension Root    | TRACE | Event: cli-client-get-version-success <json>{}</json>
2022-10-19T08:55:15.993Z | Common Extension Root    | TRACE | Found local CLI version: '1.0.20220816.2'. Expected version: '1.0.20220816.2' <json>{}</json>
2022-10-19T08:55:15.993Z | Common Extension Root    | TRACE | Local CLI has version number '1.0.20220816.2', which is equal to the required '1.0.20220816.2' <json>{}</json>
2022-10-19T08:55:15.994Z | Common Extension Root    | TRACE | Event: kubectl-client-command <json>{"args":"version --short --client -o json"}</json>
2022-10-19T08:55:16.084Z | Common Extension Root    | TRACE | Event: kubectl-client-command-success <json>{"args":"version --short --client -o json"}</json>
2022-10-19T08:55:16.084Z | Common Extension Root    | TRACE | Event: kubectl-client-get-version-success <json>{}</json>
2022-10-19T08:55:16.084Z | Common Extension Root    | TRACE | Event: binaries-utility-ensure-cli-success <json>{"isUsingLocalBinaries":"false"}</json>
2022-10-19T08:55:16.086Z | Common Extension Root    | TRACE | Event: kubectl-client-command <json>{"args":"config view --minify -o json"}</json>
2022-10-19T08:55:16.089Z | Common Extension Root    | TRACE | Event: kubectl-client-command <json>{"args":"config view --minify -o json"}</json>
2022-10-19T08:55:16.187Z | Common Extension Root    | TRACE | Event: kubectl-client-command-success <json>{"args":"config view --minify -o json"}</json>
2022-10-19T08:55:16.188Z | Common Extension Root    | TRACE | Event: kubectl-client-command <json>{"args":"config view -o jsonpath={.clusters[*].cluster.server}"}</json>
2022-10-19T08:55:16.191Z | Common Extension Root    | TRACE | Event: kubectl-client-command-success <json>{"args":"config view --minify -o json"}</json>
2022-10-19T08:55:16.282Z | Common Extension Root    | TRACE | Event: kubectl-client-command-success <json>{"args":"config view -o jsonpath={.clusters[*].cluster.server}"}</json>
2022-10-19T08:55:16.282Z | Common Extension Root    | TRACE | Event: kubernetes-panel-customizer-supported-fqdn-evaluation <json>{"currentFqdnDomain":"amazonaws.com","clustersCount":3,"fqdnDomains":"amazonaws.com,amazonaws.com,amazonaws.com"}</json>
2022-10-19T08:55:19.483Z | Common Extension Root    | TRACE | Event: cli-client-check-credentials-success <json>{}</json>
2022-10-19T08:55:19.483Z | Common Extension Root    | TRACE | Event: kubeconfig-credentials-manager-check-credentials-perf <json>{"success":true,"durationMs":3292}</json>
2022-10-19T08:55:19.484Z | Common Extension Root    | TRACE | Event: binaries-utility-try-get-binaries-success <json>{}</json>
2022-10-19T08:55:19.484Z | Common Extension Root    | TRACE | Event: kubectl-client-command <json>{"args":"config view --minify -o json"}</json>
2022-10-19T08:55:19.732Z | Common Extension Root    | TRACE | Event: kubectl-client-command-success <json>{"args":"config view --minify -o json"}</json>
2022-10-19T08:55:19.732Z | Common Extension Root    | TRACE | Event: kubectl-client-command <json>{"args":"get ingress -n default -o json"}</json>
2022-10-19T08:55:19.735Z | Common Extension Root    | TRACE | Event: kubectl-client-command <json>{"args":"get services -n default -o json"}</json>
2022-10-19T08:55:20.930Z | Common Extension Root    | TRACE | Event: binaries-utility-try-get-binaries-success <json>{}</json>
2022-10-19T08:55:20.930Z | Common Extension Root    | TRACE | Event: connect-service-task-terminal-start-connect <json>{"resourceName":"profile-service-development","ports":"3000","isolateAs":"norman-f684"}</json>
2022-10-19T08:55:20.931Z | Common Extension Root    | TRACE | Event: kubectl-client-command <json>{"args":"config view --minify -o json"}</json>
2022-10-19T08:55:21.028Z | Common Extension Root    | TRACE | Event: kubectl-client-command-success <json>{"args":"config view --minify -o json"}</json>
2022-10-19T08:55:21.028Z | Common Extension Root    | TRACE | Event: binaries-utility-try-get-binaries-success <json>{}</json>
2022-10-19T08:55:21.028Z | Common Extension Root    | TRACE | Event: binaries-utility-try-get-binaries-success <json>{}</json>
2022-10-19T08:55:21.029Z | Common Extension Root    | TRACE | Event: kubectl-client-command <json>{"args":"config view --minify -o json"}</json>
2022-10-19T08:55:21.107Z | Common Extension Root    | TRACE | Event: kubectl-client-command-success <json>{"args":"get ingress -n default -o json"}</json>
2022-10-19T08:55:21.108Z | Common Extension Root    | TRACE | Event: kubectl-client-command-success <json>{"args":"config view --minify -o json"}</json>
2022-10-19T08:55:21.201Z | Common Extension Root    | TRACE | Event: kubectl-client-command-success <json>{"args":"get services -n default -o json"}</json>
2022-10-19T08:55:21.255Z | Common Extension Root    | TRACE | Event: activation <json>{"workspacesCommonId":"ddb7fdc0-6a9e-e10f-80f4-38abe057b83c","workspaceFoldersCount":"1"}</json>
2022-10-19T08:55:21.255Z | Common Extension Root    | TRACE | Extension activated successfully <json>{}</json>
2022-10-19T08:55:24.422Z | Common Extension Root    | TRACE | Event: cli-client-refresh-credentials-success <json>{}</json>
2022-10-19T08:55:24.422Z | Connect (profile-service | TRACE | Event: kubeconfig-credentials-manager-refresh-credentials-perf <json>{"success":true,"refreshRequired":false,"durationMs":3314}</json>
2022-10-19T08:55:24.422Z | Common Extension Root    | TRACE | Event: kubectl-client-command <json>{"args":"config view --minify -o json"}</json>
2022-10-19T08:55:24.505Z | Common Extension Root    | TRACE | Event: kubectl-client-command-success <json>{"args":"config view --minify -o json"}</json>
2022-10-19T08:55:24.505Z | Connect (profile-service | TRACE | Event: connect-start-connect <json>{"resource":"profile-service-development","resourceType":"service","ports":"3000","isolateAs":"norman-f684","os":"win32"}</json>
2022-10-19T08:55:28.028Z | Common Extension Root    | TRACE | Event: cli-client-refresh-credentials-success <json>{}</json>
2022-10-19T08:55:28.029Z | Connect (profile-service | TRACE | Event: kubeconfig-credentials-manager-refresh-credentials-perf <json>{"success":true,"refreshRequired":false,"durationMs":3522}</json>
2022-10-19T08:55:28.029Z | Common Extension Root    | TRACE | Event: kubectl-client-command <json>{"args":"get namespaces -o jsonpath={.items[*].metadata.name}"}</json>
2022-10-19T08:55:29.381Z | Common Extension Root    | TRACE | Event: kubectl-client-command-success <json>{"args":"get namespaces -o jsonpath={.items[*].metadata.name}"}</json>
2022-10-19T08:55:29.381Z | Connect (profile-service | TRACE | Event: connect-validate-non-dev-spaces-cluster <json>{"isDevSpacesCluster":false}</json>
2022-10-19T08:55:35.677Z | Common Extension Root    | TRACE | Elevation requests output: [] <json>{}</json>
2022-10-19T08:55:35.677Z | Common Extension Root    | TRACE | Event: cli-client-prep-connect-success <json>{}</json>
2022-10-19T08:56:18.125Z | Common Extension Root    | ERROR | Error: cli-client-connect-error <json>{}</json> <stack>Error: Port 4318 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.\n\n	at ChildProcess.<anonymous> (c:\Users\Norman\.vscode\extensions\mindaro.mindaro-1.0.120220915\dist\extension.js:3:238027)\n	at ChildProcess.emit (node:events:526:28)\n	at ChildProcess._handle.onexit (node:internal/child_process:291:12)</stack>
2022-10-19T08:56:18.126Z | Connect (profile-service | ERROR | Error: connect-error <json>{}</json> <stack>Error: Port 4318 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.\n\n	at ChildProcess.<anonymous> (c:\Users\Norman\.vscode\extensions\mindaro.mindaro-1.0.120220915\dist\extension.js:3:238027)\n	at ChildProcess.emit (node:events:526:28)\n	at ChildProcess._handle.onexit (node:internal/child_process:291:12)</stack>
2022-10-19T08:56:18.127Z | Common Extension Root    | TRACE | Event: use-kubernetes-service-environment-variables-prompt-shown <json>{}</json>
2022-10-19T08:56:18.127Z | Common Extension Root    | ERROR | Error: connect-service-task-terminal-error <json>{}</json> <stack>Error: Failed to establish a connection. Error: Port 4318 is already in use on your machine. Please free this port and try again. Use 'netstat -ano' command to find which program is using this port.\n\n	at c:\Users\Norman\.vscode\extensions\mindaro.mindaro-1.0.120220915\dist\extension.js:3:167390\n	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)</stack>

```

**Comment by NPellet** [comment] 2022-10-19 09:20
Perhaps this could be because the endpoint is targeting different containers on the same port ?

```
norman@DESKTOP-1O37BIO:~/.kube$ kubectl describe svc simplest-collector-headless
Name:              simplest-collector-headless
Namespace:         default
Labels:            app.kubernetes.io/component=opentelemetry-collector
                   app.kubernetes.io/instance=default.simplest
                   app.kubernetes.io/managed-by=opentelemetry-operator
                   app.kubernetes.io/name=simplest-collector
                   app.kubernetes.io/part-of=opentelemetry
                   app.kubernetes.io/version=latest
Annotations:       service.beta.openshift.io/serving-cert-secret-name: simplest-collector-headless-tls
Selector:          app.kubernetes.io/component=opentelemetry-collector,app.kubernetes.io/instance=default.simplest,app.kubernetes.io/managed-by=opentelemetry-operator,app.kubernetes.io/name=simplest-collector,app.kubernetes.io/part-of=opentelemetry,app.kubernetes.io/version=latest
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                None
IPs:               None
Port:              otlp-grpc  4317/TCP
TargetPort:        4317/TCP
Endpoints:         192.168.65.47:4317
Port:              otlp-http  4318/TCP
TargetPort:        4318/TCP                                      <== HERE
Endpoints:         192.168.65.47:4318
Port:              otlp-http-legacy  55681/TCP
TargetPort:        4318/TCP                                      <== HERE
Endpoints:         192.168.65.47:4318
Session Affinity:  None
```

**Comment by elenavillamil** [comment] 2022-11-18 14:50
Hi, I just want to give a quick update for this. Fix has been merged and we are starting a release with the changes. ETA to have this released in prod is next week.

**Comment by elenavillamil** [comment] 2022-12-06 21:07
@maj, @epolar and @NPellet, fix for this has been released. I am closing this issue, but please feel free to reopen if you still see this problem.

Thank you!
Elena

**Closed by elenavillamil** 2022-12-06 21:07 UTC
Labels: bug, investigation needed
